### ISSUE TITLE
Question:  Move controller is in the floor, how do I fix that?

### ISSUE THREAD

**Issue by pupphelper** [TyborAUT/ALVR_FreePIE_scripts#6]
Hello there, I'm trying your script with ALVR, and it seems to be working, but when I start my move controller is in the floor, how to I re-centre the elevation to match my gear VR controller?

**Comment by renatopmestre** [comment]
Hey friend. If I understand correctly, your controllers are not aligned with both hands, the move controller is way off.

PSMoveSteamVRBridge (the app that connects ps move controllers to steamVR) has a reset option that goes by clicking start+select (side buttons, at the same time) with your ps move in front of your eyes/hmd/"vr goggles". Hope you can do it!

**Comment by nerionx** [comment]
When you are in steam doing room calibration are you setting your headset height to 150cm, the occulus go cannot detect height and if you don't put an offset in it will place you on floor
